# Shell variables
# Generated by 'wal'
wallpaper='/home/denis/.config/wpg/wallpapers/Waterfalls_USA_Crag_Trees_Hocking_Hills_State_Park_Ohio_Nature_10929x5553.jpg'

# Special
background='#0D0703'
foreground='#fffff5'
cursor='#fffff5'

# Colors
color0='#0D0703'
color1='#975F24'
color2='#9E754D'
color3='#728D45'
color4='#B6AB48'
color5='#94986A'
color6='#73948A'
color7='#dad9cb'
color8='#371c0a'
color9='#d07b22'
color10='#dc9754'
color11='#97c44c'
color12='#fdeb4d'
color13='#ced679'
color14='#84d1ba'
color15='#fffff5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
