wallpaper: "/home/denis/.config/wpg/wallpapers/mountains_landscapes_nature_snow_night_lights_stars_valleys_Europe_Switzerland_3840x2400.jpg"

special:
    background: "#04060D"
    foreground: "#9fb1b9"
    cursor: "#9fb1b9"

colors:
    color0: "#04060D"
    color1: "#2A455B"
    color2: "#315269"
    color3: "#3A6176"
    color4: "#4B6775"
    color5: "#818475"
    color6: "#3E6A81"
    color7: "#9fb1b9"
    color8: "#6f7b81"
    color9: "#2A455B"
    color10: "#315269"
    color11: "#3A6176"
    color12: "#4B6775"
    color13: "#818475"
    color14: "#3E6A81"
    color15: "#9fb1b9"
