# Shell variables
# Generated by 'wal'
wallpaper='/home/denis/.config/wpg/wallpapers/Wallpaper_8K_0_7680x4320.jpg'

# Special
background='#0F140A'
foreground='#bfcaac'
cursor='#bfcaac'

# Colors
color0='#0F140A'
color1='#484F37'
color2='#536733'
color3='#5A664E'
color4='#516C4C'
color5='#4A9A32'
color6='#67925D'
color7='#bfcaac'
color8='#858d78'
color9='#484F37'
color10='#536733'
color11='#5A664E'
color12='#516C4C'
color13='#4A9A32'
color14='#67925D'
color15='#bfcaac'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
