#!/bin/bash

##yay
sudo pacman -Syu
sudo pacman -S go base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay 

yay -S zsh chromium telegram-desktop mpv code thefuck antigen ruby-colorls \
 chromium-widevine ranger spotify rcm docker docker-compose antigen-git trash-cli \
  xorg-xkill xorg-xprop
yay -S neofetch nerd-fonts-dejavu-complete flameshot fzf

git config --global credential.helper libsecret

chsh -s $(which zsh)

sudo groupadd docker
sudo usermod -aG docker $USER
sudo systemctl start docker
sudo systemctl enable docker
docker volume create portainer_data
docker run -d -p 9000:9000 --name portainer --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

yay -R gedit bijiben gnome-screenshot totem  gnome-termina
