#!/bin/sh
# ~/.xprofile

# sourced at boot by xinit and display managers like lightdm

export XDG_CONFIG_HOME="$HOME/.config"

[ -d /sbin ] && PATH="$PATH:/sbin"
[ -d /usr/sbin ] && PATH="$PATH:/usr/sbin"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"

# restore the background
nitrogen --restore &

# keyring and polkit daemons
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &

# pressing super alone simulates Alt-F1
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# display timeout and sleep
xset s 1200 4300
xset dpms 1200 1300 1400

# keyboard repeat rate
xset r rate 350 60
export EDITOR=/usr/bin/nvim
[ -f /usr/bin/bat ] && export PAGER=bat
setxkbmap -model pc105 -layout us,ru -variant euro, -option  grp:shift_caps_switch grp:alt_shift_toggle numpad:microsoft eurosign:5 terminate:ctrl_alt_bksp grp:shift_caps_toggle caps:escape 
